const M=[["R_10","Volatility 10"],["1HZ10V","Volatility 10 (1s)"],["R_25","Volatility 25"],["1HZ25V","Volatility 25 (1s)"],["R_50","Volatility 50"],["1HZ50V","Volatility 50 (1s)"],["R_75","Volatility 75"],["1HZ75V","Volatility 75 (1s)"],["R_100","Volatility 100"],["1HZ90V","Volatility 90 (1s)"],["1HZ100V","Volatility 100 (1s)"],["1HZ150V","Volatility 150 (1s)"],["1HZ250V","Volatility 250 (1s)"],["1HZ1000V","Volatility 1000 (1s)"],["1HZ30V","Volatility 30 (1s)"]];
const S=["MATCHES","DIFFERS","OVER","UNDER","EVEN","ODD","DIGIT"],$=x=>document.getElementById(x);
let balance=1000,bot=false,freeS="MATCHES",cycles={},ticks={},trades=[],active=[],stats={total:0,wins:0,losses:0,stake:0,won:0,profit:0};
M.forEach(([m])=>{ticks[m]=[];cycles[m]={p:"ANALYSIS",s:10,pred:null,last:null,price:1000+Math.random()*50}});
function digit(p){return Number(p.toFixed(5).replace(/\D/g,"").slice(-1))}
function tick(m){let p=cycles[m].price||1000;p=Math.max(100,p+(Math.random()-.5)*2.5);cycles[m].price=p;let d=digit(p);ticks[m].push(d);if(ticks[m].length>250)ticks[m].shift();settle(m,d);cycles[m].s--;if(cycles[m].s<=0){if(cycles[m].p==="ANALYSIS"){cycles[m].pred=engine(m);cycles[m].p="PREDICTION";cycles[m].s=5}else if(cycles[m].p==="PREDICTION"){cycles[m].p="ENTRY";cycles[m].s=3}else{cycles[m].p="ANALYSIS";cycles[m].s=10;cycles[m].pred=null}}}
function engine(m){let a=ticks[m];if(a.length<20)return{signal:"WAIT",strategy:"WAIT",target:null,conf:0};let c=Array(10).fill(0);a.slice(-50).forEach(d=>c[d]++);let mx=Math.max(...c),d=c.indexOf(mx),base=mx/Math.max(1,Math.min(50,a.length)),even=c.filter((_,i)=>i%2===0).reduce((x,y)=>x+y,0)/Math.min(50,a.length),over=c.slice(5).reduce((x,y)=>x+y,0)/Math.min(50,a.length);let opts=[["MATCHES",base,d],["DIFFERS",1-base,d],["OVER",over,4],["UNDER",1-over,5],["EVEN",even,0],["ODD",1-even,0]].sort((x,y)=>y[1]-x[1]),o=opts[0],conf=Math.min(94,Math.round(55+o[1]*30));return{signal:conf>=68?"SIGNAL":"NO SIGNAL",strategy:o[0],target:o[2],conf,pred:d}}
function win(s,t,d){return s==="MATCHES"||s==="DIGIT"?d===t:s==="DIFFERS"?d!==t:s==="OVER"?d>t:s==="UNDER"?d<t:s==="EVEN"?d%2===0:s==="ODD"?d%2!==0:false}
function settle(m,d){active.filter(x=>x.m===m).slice().forEach(t=>{if(win(t.s,t.t,d))finish(t,true);else finish(t,false)});trades.filter(x=>!x.result&&x.m===m).forEach(x=>x.result=win(x.s,x.t,d)?"WIN":"LOSS")}
function finish(t,w){active=active.filter(x=>x!==t);let payout=w?t.stake*(t.s==="MATCHES"||t.s==="DIGIT"?8.5:.95):0,profit=payout-t.stake;balance+=payout;stats.total++;stats.stake+=t.stake;stats.won+=payout;stats.profit+=profit;w?stats.wins++:stats.losses++;trades.unshift({...t,result:w?"WIN":"LOSS",profit,closed:Date.now()});trades=trades.slice(0,100)}
function render(){let html=M.map(([m,n])=>{let c=cycles[m],a=c.pred||engine(m),pred=a.signal==="SIGNAL"?a.strategy+" "+a.target:"NO SIGNAL";return `<div class="card market"><div class="mhead"><div><h3>${n}</h3><span class="code">${m}</span></div><span class="live">● LIVE</span></div><div class="code">Live ${cycles[m].price.toFixed(5)} • Last digit ${ticks[m].at(-1)??"-"}</div><div class="cycle"><div class="cell"><small>ANALYSIS</small><div class="val count">${c.p==="ANALYSIS"?c.s+"s":"✓"}</div><small>${c.p==="ANALYSIS"?"Analyzing market":"Complete"}</small></div><div class="cell"><small>PREDICTION</small><div class="val">${pred}</div><small>${c.p==="PREDICTION"?c.s+"s":"Next cycle"}</small></div><div class="cell"><small>ENTRY</small><div class="val entry">${c.p==="ENTRY"?c.s+"s":"—"}</div><small>${c.p==="ENTRY"?"Entry window":"Waiting"}</small></div><div class="cell"><small>LAST RESULT</small><div class="val ${c.last==="WIN"?"win":c.last==="LOSS"?"loss":""}">${c.last||"—"}</div><small>${a.conf||0}% confidence</small></div></div><div class="next">${c.p==="ANALYSIS"?"NEXT PREDICTION IN "+c.s+"s":c.p==="PREDICTION"?"ENTRY OPENS IN "+c.s+"s":"ENTRY WINDOW "+c.s+"s"}</div></div>`}).join("");$("markets").innerHTML=html;$("balance").textContent="$"+balance.toFixed(2);$("total").textContent=stats.total;$("wins").textContent=stats.wins;$("losses").textContent=stats.losses;$("accuracy").textContent=stats.total?Math.round(stats.wins/stats.total*100)+"%":"0%";$("active").innerHTML=active.map(t=>`<div class="card">${t.source} • ${t.m} • ${t.s} ${t.t} • $${t.stake}</div>`).join("")||"None";renderFree();renderHistory()}
function renderFree(){let a=engine("R_100");$("freeMarket").textContent="R_100";$("freePred").textContent=a.signal==="SIGNAL"?freeS+" "+(freeS==="OVER"||freeS==="UNDER"?a.target:a.pred):"NO SIGNAL";$("freeConf").textContent=a.conf+"% confidence";$("freeReason").textContent="Demo statistical signal using recent digit distribution. Not a guarantee.";$("freeList").innerHTML=M.map(([m,n])=>{let x=engine(m),v=x.signal==="SIGNAL"?freeS+" "+((freeS==="OVER"||freeS==="UNDER")?x.target:x.pred):"NO SIGNAL";return `<div class="card"><b>${n}</b><span class="code"> ${m}</span><div class="focus" style="font-size:22px;font-weight:900;padding:8px">${v}</div><div class="next">${cycles[m].p==="ANALYSIS"?"NEXT PREDICTION IN "+cycles[m].s+"s":cycles[m].p==="PREDICTION"?"ENTRY IN "+cycles[m].s+"s":"ENTRY WINDOW "+cycles[m].s+"s"}</div></div>`}).join("")}
function renderHistory(){$("hstake").textContent="$"+stats.stake.toFixed(2);$("hwon").textContent="$"+stats.won.toFixed(2);$("hprofit").textContent="$"+stats.profit.toFixed(2);$("session").textContent="$"+stats.profit.toFixed(2);$("historyList").innerHTML=trades.map(t=>`<div class="card">${new Date(t.closed).toLocaleTimeString()} • ${t.m}<br>${t.s} ${t.t} • Stake $${t.stake} • <b class="${t.result==="WIN"?"win":"loss"}">${t.result}</b> • $${t.profit.toFixed(2)}</div>`).join("")||"<p class='muted'>No completed demo trades.</p>"}
function trade(m,s,t,source,stake){if(stake>balance){toast("Insufficient paper balance.");return}balance-=stake;active.push({m,s,t,stake,source})}
function useAI(){let a=engine($("manualMarket").value);if(a.signal!=="SIGNAL"){toast("NO SIGNAL");return}let s=a.strategy;$("strategy").value=s;$("target").value=(s==="OVER"||s==="UNDER")?a.target:a.pred;toast("AI prediction loaded")}
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2000)}
function fillSelect(id){$(id).innerHTML=M.map(x=>`<option value="${x[0]}">${x[1]} (${x[0]})</option>`).join("")}
function start(){bot=true;$("botStatus").textContent="RUNNING";toast("AI Bot started — demo only")}
function stop(){bot=false;$("botStatus").textContent="STOPPED";toast("AI Bot stopped")}
function botCycle(){if(!bot)return;let m=$("botMarket").value,a=engine(m),s=$("botStrategy").value;if(a.signal==="SIGNAL"){s=s==="AUTO"?a.strategy:s;let t=(s==="OVER"||s==="UNDER")?a.target:a.pred;trade(m,s,t,"AI BOT",Math.max(.25,+$("botStake").value||1))}}
document.addEventListener("DOMContentLoaded",()=>{fillSelect("botMarket");fillSelect("manualMarket");for(let i=0;i<120;i++)M.forEach(([m])=>tick(m));document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(b.dataset.p).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));$(b.dataset.t).classList.add("active");document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});document.querySelectorAll("#strategies button").forEach(b=>b.onclick=()=>{freeS=b.dataset.s;document.querySelectorAll("#strategies button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("useAI").onclick=useAI;$("freeUse").onclick=()=>{$("manualMarket").value="R_100";useAI()};$("place").onclick=()=>{let t=+$("target").value;if(!Number.isInteger(t)||t<0||t>9)return toast("Enter a digit/barrier 0–9");trade($("manualMarket").value,$("strategy").value,t,"MANUAL",Math.max(.25,+$("stake").value||1))};$("start").onclick=start;$("stop").onclick=stop;$("theme").onclick=()=>{document.body.classList.toggle("light");localStorage.kwlight=document.body.classList.contains("light")};$("clear").onclick=()=>{if(confirm("Clear demo history?")){trades=[];active=[];balance=1000;stats={total:0,wins:0,losses:0,stake:0,won:0,profit:0}}};if(localStorage.kwlight==="true")document.body.classList.add("light");setInterval(()=>{M.forEach(([m])=>tick(m));if(bot)botCycle();render()},1000);render()});